export const APP_LOAD = 'APP_LOAD';
export const GET_ARTICLES = 'GET_ARTICLES';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLE_ID = 'SET_ARTICLE_ID';

export const SET_USER_DATA = 'SET_USER_DATA';

export const CREATE_FAVORITE = 'CREATE_FAVORITE';
export const SET_FAVORITES = 'SET_FAVORITE';
export const SET_NAVIGAGED_FROM_FAVORITES = 'SET_NAVIGAGED_FROM_FAVORITES';
